site_name: Rehoboth Audio Manual
site_author: Arjen Rouvoet
site_url: https://ajrouvoet.github.io/audioman.md/

theme:
  name: material
  palette:
    scheme: slate
    primary: brown
  features:
    - navigation.indexes

docs_dir: docs/audio/

markdown_extensions:
  - attr_list
  - smarty # for ascii to unicode/html entities conversion of symbols (e.g. emdash ---)
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
